name: "Update headers"
on:
  pull_request_target:
    # branches:
    #   - master
  # pull_request:
  #   branches:
  #     - master
    paths:
      - "ibm_db2.stub.php"
      - "ibm_db2_arginfo.h"
      - "ibm_db2_legacy_arginfo.h"
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.2"
      - name: "Update headers"
        run: |
          wget https://raw.githubusercontent.com/php/php-src/php-8.2.3/build/gen_stub.php
          HEADERS_IN_SYNC=$(php gen_stub.php .)
          if [[ ! -z $HEADERS_IN_SYNC ]]; then echo 'Headers are not in sync with "ibm_db2.stub.php", updating.'; fi;
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ibm_db2_arginfo.h ibm_db2_legacy_arginfo.h
          git commit -m "Update headers"
          # git push origin "${GITHUB_REF}"
          git push origin ${{ github.head_ref }}
          # git push origin ${{ github.ref_name }}
